openapi: '3.0.0'
info:
  title: kytos/maintenance_window
  version: '0.2'
  description: >-
    **Warning**: *This documentation is experimental and may change soon.*


    Create maintenance windows to allow the maintenance of items in the network
    without error notifications and keeping, where possible, the network circuits
    operating.

servers:
  - url: '<KYTOS_URL>/api/kytos'
    description: 'Test server'
tags:
  - name: List
  - name: Add
  - name: Update
  - name: Delete
paths:
  '/maintenance':
    get:
      tags:
        - List
      summary: Retrieve a list of all maintenance windows.
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MaintenanceWindow'
    post:
      tags:
        - Add
      summary: Insert a new maintenance window
      requestBody:
        description: Maintenance window to be created.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceWindow'
      responses:
        '201':
           description: Maintenance window created.
           content:
             application/json:
               schema:
                type: object
                properties:
                  mw_id:
                    type: string
        '400':
           description: Invalid JSON or invalid start/end dates.
           content:
             application/json:
               schema:
                type: object
                properties:
                  mw_id:
                    type: string
        '415':
           description: No JSON in request.
           content:
             application/json:
               schema:
                type: object
                properties:
                  mw_id:
                    type: string
  '/maintenance/{mw_id}':
    get:
      tags:
        - List
      summary: Retrive the Maintenance window with the given id
      parameters:
        - name: mw_id
          in: path
          required: true
          schema:
            type: string
          description: Maintenance window ID
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceWindow'
        '404':
          description: Maintenance window not found.
    patch:
      tags:
        - Update
      summary: Update the Maintenance window with the given id
      parameters:
        - name: mw_id
          in: path
          required: true
          schema:
            type: string
          description: Maintenance window ID
      requestBody:
        description: Maintenance window fields to be modified.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceWindow'
      responses:
        '200':
          description: Maintenance window sucessfully updated
        '400':
          description: Malformed request body
        '404':
          description: Maintenance window not found.
        '415':
          description: No JSON in request.
    delete:
      tags:
        - Delete
      summary: Remove the Maintenance window with given id
      parameters:
        - name: mw_id
          in: path
          required: true
          schema:
            type: string
          description: Maintenance window ID
      responses:
        '200':
          description: Maintenance window deleted.
        '400':
          description: Invalid JSON.
        '404':
          description: Maintenance window not found.
  '/maintenance/{mw_id}/end':
    patch:
      tags:
        - Update
      summary: Finish a maintenance window right now
      parameters:
        - name: mw_id
          in: path
          required: true
          schema:
            type: string
          description: Maintenance window ID
      responses:
        '200':
          description: Maintenance window succesfully finished
        '400':
          description: Invalid data.
        '404':
          description: Maintenance window not found.
        '415':
          description: No JSON in request.
  '/maintenance/{mw_id}/extend':
    patch:
      tags:
        - Update
      summary: Extend the duration of a running maintenance
      parameters:
        - name: mw_id
          in: path
          required: true
          schema:
            type: string
          description: Maintenance window ID
      requestBody:
        description: Minutes to extend the maintenance
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                minutes:
                  type: integer        
      responses:
        '200':
          description: Maintenance window succesfully extended
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
  '/maintenance/report':
    post:
      tags:
        - List
      summary: Simulate a maintenance and return a report with affected .
      requestBody:
        description: Maintenance window to be simulated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceWindow'
      responses:
        '200':
           description: Report.
           content:
             application/json:
               schema:
                type: object
                properties:
                  mw_id:
                    type: string
        '400':
           description: Invalid JSON.
components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    BadRequest:
      description: Received data is invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    UnsupportedMediaType:
      description: The content-type is not supported
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
  schemas:
    ErrorMessage:
      additionalProperties: false
      type: object
      properties:
        code:
          type: integer
        name:
          type: string
        description:
          type: string
      required:
        - code
        - name
        - description
    MaintenanceWindow:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        items:
          type: array
          items:
            oneOf:
              - type: string
                format: '00:00:00:00:00:00:00:00'
              - $ref: '#/components/schemas/Endpoint'
              - $ref: '#/components/schemas/Link'
    Tag: # Can be referenced via '#/components/schemas/Tag'
      type: object
      additionalProperties: false
      required:
        - tag_type
        - value
      properties:
        tag_type:
          type: string
        value:
          type: string
    Endpoint: # Can be referenced via '#/components/schemas/Endpoint'
      type: object
      additionalProperties: false
      required:
        - interface_id
      properties:
        interface_id:
          type: string
          format: '00:00:00:00:00:00:00:00:0'
        tag:
          $ref: '#/components/schemas/Tag'
    Link: # Can be referenced via '#/components/schemas/Link'
      type: object
      additionalProperties: false
      required:
        - id
        - endpoint_a
        - endpoint_b
      properties:
        id:
          type: string
        endpoint_a:
          $ref: '#/components/schemas/Endpoint'
        endpoint_b:
          $ref: '#/components/schemas/Endpoint'
